// ============================================================
//  LMU SETUPS — seeds.js
//  Exemplos de setup para demonstração visual
//  Só popula se o localStorage estiver vazio.
// ============================================================

const SEED_SETUPS = [
  {
    id: 'seed-001',
    classId: 'hypercar',
    carId: 'ferrari_499p',
    carYear: '2024',
    trackId: 'le_mans',
    trackLayout: 'Full Circuit',
    condition: 'dry',
    sessionType: 'endurance',
    series: 'wec',
    brakeBias: 56.5,
    tc: 5,
    tcPowerCut: 6,
    tcSlipAngle: 4,
    abs: 3,
    brakePressure: 88,
    engineMap: 3,
    fuelMap: 2,
    laptime: '3:27:545',
    date: '2026-06-10',
    rating: 5,
    notes: 'Setup muito bom para a corrida de endurance. BB em 56.5 funcionou ótimo nas frenagens da Dunlop e Ford. TC 5 deixa o carro controlado sem perder saída de curva. ABS 3 evitou travamentos na Porsche e Arnage. Recomendo como base.',
    createdAt: '2026-06-10T14:30:00Z',
    updatedAt: '2026-06-10T14:30:00Z',
  },
  {
    id: 'seed-002',
    classId: 'lmgt3',
    carId: 'porsche_992_gt3',
    carYear: '2025',
    trackId: 'spa',
    trackLayout: 'Grand Prix',
    condition: 'dry',
    sessionType: 'qualifying',
    series: 'wec',
    brakeBias: 58.0,
    tc: 4,
    tcPowerCut: 5,
    tcSlipAngle: 5,
    abs: 4,
    brakePressure: 92,
    engineMap: 4,
    fuelMap: 1,
    laptime: '2:15:320',
    date: '2026-05-28',
    rating: 4,
    notes: 'Bom setup para qualifying em Spa. BB um pouco mais alto ajuda na frenagem do Raidillon. Em corrida seria melhor baixar TC para 5 e Fuel Map para 2 para economizar combustível.',
    createdAt: '2026-05-28T10:15:00Z',
    updatedAt: '2026-05-28T10:15:00Z',
  },
  {
    id: 'seed-003',
    classId: 'lmp2',
    carId: 'oreca_07',
    carYear: '2024',
    trackId: 'interlagos',
    trackLayout: 'Grand Prix',
    condition: 'wet',
    sessionType: 'sprint',
    series: 'wec',
    brakeBias: 54.0,
    tc: 8,
    tcPowerCut: 9,
    tcSlipAngle: 7,
    abs: 7,
    brakePressure: 78,
    engineMap: 5,
    fuelMap: 3,
    laptime: '1:46:890',
    date: '2026-04-17',
    rating: 3,
    notes: 'Pista molhada em Interlagos é muito escorregadia. TC alto e BB mais baixo ajudaram a controlar. Ainda escorrega bastante no S3, talvez aumentar TC Slip Angle para 8 na próxima.',
    createdAt: '2026-04-17T09:00:00Z',
    updatedAt: '2026-04-17T09:00:00Z',
  },
  {
    id: 'seed-004',
    classId: 'hypercar',
    carId: 'toyota_gr010',
    carYear: '2023',
    trackId: 'bahrain',
    trackLayout: 'Endurance Circuit',
    condition: 'dry',
    sessionType: 'endurance',
    series: 'wec',
    brakeBias: 55.5,
    tc: 6,
    tcPowerCut: 6,
    tcSlipAngle: 5,
    abs: 4,
    brakePressure: 90,
    engineMap: 3,
    fuelMap: 3,
    laptime: '1:48:123',
    date: '2026-02-24',
    rating: 4,
    notes: 'Setup sólido para o circuito de endurance do Bahrein. Clima quente afeta os pneus, então mantive Brake Pressure em 90% para evitar superaquecimento. TC 6 funciona bem nas chicanes.',
    createdAt: '2026-02-24T16:45:00Z',
    updatedAt: '2026-02-24T16:45:00Z',
  },
  {
    id: 'seed-005',
    classId: 'lmgt3',
    carId: 'mclaren_720s',
    carYear: '2024',
    trackId: 'silverstone',
    trackLayout: 'WEC Grand Prix',
    condition: 'dry',
    sessionType: 'qualifying',
    series: 'wec',
    brakeBias: 57.0,
    tc: 3,
    tcPowerCut: 4,
    tcSlipAngle: 4,
    abs: 3,
    brakePressure: 95,
    engineMap: 5,
    fuelMap: 1,
    laptime: '2:01:441',
    date: '2026-05-10',
    rating: 5,
    notes: 'Excelente! McLaren em Silverstone é um sonho. TC baixo (3) dá liberdade de sobresaída nas saídas de curva, especialmente Copse e Maggots. BB 57 funciona bem na frenagem da Village. Meu melhor quali até agora.',
    createdAt: '2026-05-10T11:30:00Z',
    updatedAt: '2026-05-10T11:30:00Z',
  },
  {
    id: 'seed-006',
    classId: 'hypercar',
    carId: 'alpine_a424',
    carYear: '2024',
    trackId: 'fuji',
    trackLayout: 'Grand Prix',
    condition: 'mixed',
    sessionType: 'sprint',
    series: 'wec',
    brakeBias: 54.5,
    tc: 7,
    tcPowerCut: 7,
    tcSlipAngle: 6,
    abs: 5,
    brakePressure: 82,
    engineMap: 4,
    fuelMap: 3,
    laptime: '1:34:712',
    date: '2026-04-05',
    rating: 3,
    notes: 'Condições mistas em Fuji são complicadas. BB mais baixo para evitar travamentos com pneus frios. TC 7 necessário com pista molhando e secando. Próxima vez tentar subir para 8 no início e ir baixando.',
    createdAt: '2026-04-05T08:20:00Z',
    updatedAt: '2026-04-05T08:20:00Z',
  },
  {
    id: 'seed-007',
    classId: 'hypercar',
    carId: 'porsche_963',
    carYear: '2024',
    trackId: 'sebring',
    trackLayout: 'Full Circuit',
    condition: 'dry',
    sessionType: 'endurance',
    series: 'wec',
    brakeBias: 57.5,
    tc: 5,
    tcPowerCut: 5,
    tcSlipAngle: 5,
    abs: 4,
    brakePressure: 87,
    engineMap: 3,
    fuelMap: 2,
    laptime: '1:52:334',
    date: '2026-03-15',
    rating: 4,
    notes: 'Sebring é muito abrasiva para os freios. Brake Pressure em 87 ajudou muito na durabilidade. TC 5 no início da corrida, mas tive que subir para 6 com desgaste mais avançado.',
    createdAt: '2026-03-15T15:00:00Z',
    updatedAt: '2026-03-15T15:00:00Z',
  },
  {
    id: 'seed-008',
    classId: 'lmp3',
    carId: 'ginetta_g61',
    carYear: '2024',
    trackId: 'barcelona',
    trackLayout: 'Grand Prix',
    condition: 'dry',
    sessionType: 'sprint',
    series: 'elms',
    brakeBias: 59.0,
    tc: 6,
    tcPowerCut: 7,
    tcSlipAngle: 5,
    abs: null,
    brakePressure: 93,
    engineMap: 3,
    fuelMap: 2,
    laptime: '1:52:001',
    date: '2026-06-01',
    rating: 3,
    notes: 'LMP3 sem ABS é desafiador em Barcelona. BB mais alto (59) compensa a tendência de sobresaída do Ginetta. Cuidado na curva 1 e 5, fácil de travar. TC 6 suficiente para ELMS.',
    createdAt: '2026-06-01T12:00:00Z',
    updatedAt: '2026-06-01T12:00:00Z',
  },
  {
    id: 'seed-009',
    classId: 'lmgt3',
    carId: 'ferrari_296_gt3',
    carYear: '2024',
    trackId: 'le_mans',
    trackLayout: 'Full Circuit',
    condition: 'dry',
    sessionType: 'endurance',
    series: 'wec',
    brakeBias: 56.0,
    tc: 5,
    tcPowerCut: 6,
    tcSlipAngle: 4,
    abs: 4,
    brakePressure: 86,
    engineMap: 3,
    fuelMap: 2,
    laptime: '3:52:114',
    date: '2026-06-14',
    rating: 4,
    notes: 'Ferrari LMGT3 em Le Mans é muito divertida. Na reta dos Hunaudières não precisa de ABS alto, mas nas chicanes a 4 funciona bem. BB 56 dá equilíbrio bom para a curva Ford.',
    createdAt: '2026-06-14T17:30:00Z',
    updatedAt: '2026-06-14T17:30:00Z',
  },
  {
    id: 'seed-010',
    classId: 'hypercar',
    carId: 'peugeot_9x8_24',
    carYear: '2024',
    trackId: 'spa',
    trackLayout: 'Endurance',
    condition: 'dry',
    sessionType: 'qualifying',
    series: 'wec',
    brakeBias: 55.0,
    tc: 4,
    tcPowerCut: 5,
    tcSlipAngle: 4,
    abs: 3,
    brakePressure: 91,
    engineMap: 5,
    fuelMap: 1,
    laptime: '2:02:889',
    date: '2026-05-30',
    rating: 5,
    notes: 'Peugeot 9X8 com asa em Spa é brutal! TC 4 em qualifying dá liberdade total no Eau Rouge. BB 55 ligeiramente traseiro para melhor rotação no Bus Stop. Um dos meus melhores qualis!',
    createdAt: '2026-05-30T13:45:00Z',
    updatedAt: '2026-05-30T13:45:00Z',
  },
];

// Popula localStorage apenas se estiver vazio
(function seedIfEmpty() {
  if (typeof Storage === 'undefined' || typeof LMU_DATA === 'undefined') return;
  if (Storage.getAll().length > 0) return;
  Storage._persist(SEED_SETUPS);
  console.log('[Seeds] 10 setups de exemplo carregados.');
})();
