import json
import urllib.request

url = "https://onfghiehtyswvhwpcwct.supabase.co/rest/v1/setups"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZmdoaWVodHlzd3Zod3Bjd2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2OTY0OTksImV4cCI6MjA5NzI3MjQ5OX0.3zmG-hXZq2fJsg-N04JhzbV3dn0PjNDrPEHjOWoejUE"

headers = {
    "apikey": anon_key,
    "Authorization": f"Bearer {anon_key}",
    "Content-Type": "application/json",
    "Prefer": "resolution=merge-duplicates"
}

seed_setups = [
  {
    "id": "seed-001",
    "class_id": "hypercar",
    "car_id": "ferrari_499p",
    "car_year": "2024",
    "track_id": "le_mans",
    "track_layout": "Full Circuit",
    "condition": "dry",
    "session_type": "endurance",
    "series": "wec",
    "brake_bias": 56.5,
    "tc": 5,
    "tc_power_cut": 6,
    "tc_slip_angle": 4,
    "abs": 3,
    "brake_pressure": 88,
    "laptime": "3:27:545",
    "date": "2026-06-10",
    "rating": 5,
    "notes": "Setup muito bom para a corrida de endurance. BB em 56.5 funcionou ótimo nas frenagens da Dunlop e Ford. TC 5 deixa o carro controlado sem perder saída de curva. ABS 3 evitou travamentos na Porsche e Arnage. Recomendo como base.",
    "created_at": "2026-06-10T14:30:00Z",
    "updated_at": "2026-06-10T14:30:00Z"
  },
  {
    "id": "seed-002",
    "class_id": "lmgt3",
    "car_id": "porsche_992_gt3",
    "car_year": "2025",
    "track_id": "spa",
    "track_layout": "Grand Prix",
    "condition": "dry",
    "session_type": "qualifying",
    "series": "wec",
    "brake_bias": 58.0,
    "tc": 4,
    "tc_power_cut": 5,
    "tc_slip_angle": 5,
    "abs": 4,
    "brake_pressure": 92,
    "laptime": "2:15:320",
    "date": "2026-05-28",
    "rating": 4,
    "notes": "Bom setup para qualifying em Spa. BB um pouco mais alto ajuda na frenagem do Raidillon. Em corrida seria melhor baixar TC para 5 e Fuel Map para 2 para economizar combustível.",
    "created_at": "2026-05-28T10:15:00Z",
    "updated_at": "2026-05-28T10:15:00Z"
  },
  {
    "id": "seed-003",
    "class_id": "lmp2",
    "car_id": "oreca_07",
    "car_year": "2024",
    "track_id": "interlagos",
    "track_layout": "Grand Prix",
    "condition": "wet",
    "session_type": "sprint",
    "series": "wec",
    "brake_bias": 54.0,
    "tc": 8,
    "tc_power_cut": 9,
    "tc_slip_angle": 7,
    "abs": 7,
    "brake_pressure": 78,
    "laptime": "1:46:890",
    "date": "2026-04-17",
    "rating": 3,
    "notes": "Pista molhada em Interlagos é muito escorregadia. TC alto e BB mais baixo ajudaram a controlar. Ainda escorrega bastante no S3, talvez aumentar TC Slip Angle para 8 na próxima.",
    "created_at": "2026-04-17T09:00:00Z",
    "updated_at": "2026-04-17T09:00:00Z"
  },
  {
    "id": "seed-004",
    "class_id": "hypercar",
    "car_id": "toyota_gr010",
    "car_year": "2023",
    "track_id": "bahrain",
    "track_layout": "Endurance Circuit",
    "condition": "dry",
    "session_type": "endurance",
    "series": "wec",
    "brake_bias": 55.5,
    "tc": 6,
    "tc_power_cut": 6,
    "tc_slip_angle": 5,
    "abs": 4,
    "brake_pressure": 90,
    "laptime": "1:48:123",
    "date": "2026-02-24",
    "rating": 4,
    "notes": "Setup sólido para o circuito de endurance do Bahrein. Clima quente afeta os pneus, então mantive Brake Pressure em 90% para evitar superaquecimento. TC 6 funciona bem nas chicanes.",
    "created_at": "2026-02-24T16:45:00Z",
    "updated_at": "2026-02-24T16:45:00Z"
  },
  {
    "id": "seed-005",
    "class_id": "lmgt3",
    "car_id": "mclaren_720s",
    "car_year": "2024",
    "track_id": "silverstone",
    "track_layout": "WEC Grand Prix",
    "condition": "dry",
    "session_type": "qualifying",
    "series": "wec",
    "brake_bias": 57.0,
    "tc": 3,
    "tc_power_cut": 4,
    "tc_slip_angle": 4,
    "abs": 3,
    "brake_pressure": 95,
    "laptime": "2:01:441",
    "date": "2026-05-10",
    "rating": 5,
    "notes": "Excelente! McLaren em Silverstone é um sonho. TC baixo (3) dá liberdade de sobresaída nas saídas de curva, especialmente Copse e Maggots. BB 57 funciona bem na frenagem da Village. Meu melhor quali até agora.",
    "created_at": "2026-05-10T11:30:00Z",
    "updated_at": "2026-05-10T11:30:00Z"
  },
  {
    "id": "seed-006",
    "class_id": "hypercar",
    "car_id": "alpine_a424",
    "car_year": "2024",
    "track_id": "fuji",
    "track_layout": "Grand Prix",
    "condition": "mixed",
    "session_type": "sprint",
    "series": "wec",
    "brake_bias": 54.5,
    "tc": 7,
    "tc_power_cut": 7,
    "tc_slip_angle": 6,
    "abs": 5,
    "brake_pressure": 82,
    "laptime": "1:34:712",
    "date": "2026-04-05",
    "rating": 3,
    "notes": "Condições mistas em Fuji são complicadas. BB mais baixo para evitar travamentos com pneus frios. TC 7 necessário com pista molhando e secando. Próxima vez tentar subir para 8 no início e ir baixando.",
    "created_at": "2026-04-05T08:20:00Z",
    "updated_at": "2026-04-05T08:20:00Z"
  },
  {
    "id": "seed-007",
    "class_id": "hypercar",
    "car_id": "porsche_963",
    "car_year": "2024",
    "track_id": "sebring",
    "track_layout": "Full Circuit",
    "condition": "dry",
    "session_type": "endurance",
    "series": "wec",
    "brake_bias": 57.5,
    "tc": 5,
    "tc_power_cut": 5,
    "tc_slip_angle": 5,
    "abs": 4,
    "brake_pressure": 87,
    "laptime": "1:52:334",
    "date": "2026-03-15",
    "rating": 4,
    "notes": "Sebring é muito abrasiva para os freios. Brake Pressure em 87 ajudou muito na durabilidade. TC 5 no início da corrida, mas tive que subir para 6 com desgaste mais avançado.",
    "created_at": "2026-03-15T15:00:00Z",
    "updated_at": "2026-03-15T15:00:00Z"
  },
  {
    "id": "seed-008",
    "class_id": "lmp3",
    "car_id": "ginetta_g61",
    "car_year": "2024",
    "track_id": "barcelona",
    "track_layout": "Grand Prix",
    "condition": "dry",
    "session_type": "sprint",
    "series": "elms",
    "brake_bias": 59.0,
    "tc": 6,
    "tc_power_cut": 7,
    "tc_slip_angle": 5,
    "abs": None,
    "brake_pressure": 93,
    "laptime": "1:52:001",
    "date": "2026-06-01",
    "rating": 3,
    "notes": "LMP3 sem ABS é desafiador em Barcelona. BB mais alto (59) compensa a tendência de sobresaída do Ginetta. Cuidado na curva 1 e 5, fácil de travar. TC 6 suficiente para ELMS.",
    "created_at": "2026-06-01T12:00:00Z",
    "updated_at": "2026-06-01T12:00:00Z"
  },
  {
    "id": "seed-009",
    "class_id": "lmgt3",
    "car_id": "ferrari_296_gt3",
    "car_year": "2024",
    "track_id": "le_mans",
    "track_layout": "Full Circuit",
    "condition": "dry",
    "session_type": "endurance",
    "series": "wec",
    "brake_bias": 56.0,
    "tc": 5,
    "tc_power_cut": 6,
    "tc_slip_angle": 4,
    "abs": 4,
    "brake_pressure": 86,
    "laptime": "3:52:114",
    "date": "2026-06-14",
    "rating": 4,
    "notes": "Ferrari LMGT3 em Le Mans é muito divertida. Na reta dos Hunaudières não precisa de ABS alto, mas nas chicanes a 4 funciona bem. BB 56 dá equilíbrio bom para a curva Ford.",
    "created_at": "2026-06-14T17:30:00Z",
    "updated_at": "2026-06-14T17:30:00Z"
  },
  {
    "id": "seed-010",
    "class_id": "hypercar",
    "car_id": "peugeot_9x8_24",
    "car_year": "2024",
    "track_id": "spa",
    "track_layout": "Endurance",
    "condition": "dry",
    "session_type": "qualifying",
    "series": "wec",
    "brake_bias": 55.0,
    "tc": 4,
    "tc_power_cut": 5,
    "tc_slip_angle": 4,
    "abs": 3,
    "brake_pressure": 91,
    "laptime": "2:02:889",
    "date": "2026-05-30",
    "rating": 5,
    "notes": "Peugeot 9X8 com asa em Spa é brutal! TC 4 em qualifying dá liberdade total no Eau Rouge. BB 55 ligeiramente traseiro para melhor rotação no Bus Stop. Um dos meus melhores qualis!",
    "created_at": "2026-05-30T13:45:00Z",
    "updated_at": "2026-05-30T13:45:00Z"
  }
]

data = json.dumps(seed_setups).encode('utf-8')
req = urllib.request.Request(url, data=data, headers=headers, method="POST")

try:
    with urllib.request.urlopen(req) as response:
        print("Status Code:", response.getcode())
        print("Response:", response.read().decode('utf-8'))
except Exception as e:
    print("Error:", e)
